### ISSUE TITLE
Animated logo

### ISSUE THREAD

**Issue by ChiyoOsaka** [WikiMissing/mw-config#8]
Work out how the logo is animated on https://test.wikipedia.org/wiki/Main_Page

**Comment by nyuszika7h** [comment]
That's a CSS overlay:

```css
#p-logo::before {
    content: "TESTSITE";
    display: block;
    position: absolute;
    bottom: 0;
    background: #C6FFE0;
    color: #333;
    font: bold 17px/1 sans-serif;
    opacity: 0.9;
    border: 3px solid #007092;
    border-radius: 2em;
    text-align: center;
    padding: 0.5em 1em;
    box-sizing: border-box;
    width: 100%;
    transform: rotate(-10deg);
    letter-spacing: 4px;
    pointer-events: none;
    transition: transform 1s ease;
}
```
